version: "3.8"
services:
  spring-boot:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb
    networks:
      - comment
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: customer
      MYSQL_USER: rasit
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - comment
networks:
  comment:
    driver: bridge